// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taokuapzuxmtpznvkuuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhb2t1YXB6dXhtdHB6bnZrdXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTYwMzAsImV4cCI6MjA2NTc3MjAzMH0.5w1OAmT2wQD5vnBKwuDe3BUVzwQYKVMgVFl4whQ7WlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);